apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  SESSION_SECRET: "fHk8YdDnwfqmF3BROwQ4Qo9CAvNpoy4SePOHK2Sr/5E="
  DB_PASSWORD: "rohit12345"